baseURL = "https://lizziew.github.io/"
title = "Elizabeth Wei"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  style = "default"
  description = "Elizabeth Wei's Portfolio"
  copyright = "&copy;2024 Elizabeth Wei"
  sidebarAbout = [
    "I'm a software engineer based in San Francisco."
  ]
  email = ""

  # Nav links in the side bar - keeping only About and Projects
  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = true

  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"
  home = false

  [params.social]
  linkedin = "https://www.linkedin.com/in/elizabeth-wei/"
  github = "https://github.com/lizziew"
  blog = "http://datasieve.blogspot.com/"
