baseURL = "https://lizziew.github.io/"
title = "Elizabeth Wei"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  style = "default"
  description = "Elizabeth Wei's Portfolio"
  copyright = "&copy;2024 Elizabeth Wei"
  sidebarAbout = [
    "I'm a software engineer based in San Francisco."
  ]
  email = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = true

  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"
  home = false

  # Social buttons in the sidebar
  [params.social]
  linkedin      = "https://www.linkedin.com/in/elizabeth-wei/"
  github        = "https://github.com/lizziew"
  whatsapp      = "http://datasieve.blogspot.com/"  # Using WhatsApp button for blog link as requested

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^hugo$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
